RemoteConnectionQueueApp/Controllers/ConnectionsController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RemoteConnectionQueueApp.Areas.Identity.Data;
using RemoteConnectionQueueApp.Data;
using RemoteConnectionQueueApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RemoteConnectionQueueApp.Controllers
{
    public class ConnectionsController : Controller
    {

        private readonly ApplicationDbContext _db;
        private readonly INotyfService _notyf;

        [BindProperty]
        public RemoteConnection RemoteConnection { get; set; }

        public IEnumerable<Queue> Queues { get; set; }

        public ConnectionsController(ApplicationDbContext db, INotyfService notyf)
        {
            _db = db;
            _notyf = notyf;
        }

        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Connect(int id)
        {

            RemoteConnection rc = await _db.RemoteConnection.FirstOrDefaultAsync(u => u.Id == id);

            return View(rc);
        }
        public async Task<IActionResult> JoinQueue(int id)
        {

            //queue = _db.Queue.FirstOrDefault(u => u.RemoteConnectionId == id);

            Queues = await _db.Queue.Where(u => u.RemoteConnectionId == id).ToListAsync();

            ViewBag.RemoteConnectionId = id;

            return View(Queues);
        }

        public IActionResult ChangeQueue(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            //Check if already connected
            RemoteConnection = new RemoteConnection();
            RemoteConnection = _db.RemoteConnection.FirstOrDefault(u => u.Id == id);

            if (RemoteConnection == null)
            {
                return NotFound();
            }
            else
            {
                if (RemoteConnection.BagliKisi == User.Identity.Name)
                {
                    _notyf.Error("Zaten bağlısınız.");
                    return RedirectToAction("Index");
                }
            }

            Queue queue = new Queue();

            //Check if already in queue:
            queue = _db.Queue.FirstOrDefault(i => i.RemoteConnectionId == id && i.BekleyenKisi == User.Identity.Name);

            if (queue == null)
            {
                //Not in queue. Add.
                Queue queue1 = new Queue();
                queue1.BekleyenKisi = User.Identity.Name;
                queue1.RemoteConnectionId = id;
                _db.Queue.Add(queue1);
                _db.SaveChanges();
            }
            else
            {
                //User in queue. Remove.
                _db.Queue.Remove(queue);
                _db.SaveChanges();
            }
            
            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult Upsert(int? id)
        {
            RemoteConnection = new RemoteConnection();
            if (id == null)
            {
                //create
                return View(RemoteConnection);
            }
            //update
            RemoteConnection = _db.RemoteConnection.FirstOrDefault(u => u.Id == id);
            if (RemoteConnection == null)
            {
                return NotFound();
            }
            return View(RemoteConnection);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Connect()
        {
            if (ModelState.IsValid)
            {
                RemoteConnection.BagliKisi = User.Identity.Name;
                RemoteConnection.BaglantiZamani = DateTime.Now;
                _db.RemoteConnection.Update(RemoteConnection);

                //Remove if in queue
                Queue queue = new Queue();

                queue = _db.Queue.FirstOrDefault(i => i.RemoteConnectionId == RemoteConnection.Id && i.BekleyenKisi == User.Identity.Name);

                if (queue != null)
                {
                    //User in queue. Remove.
                    _db.Queue.Remove(queue);
                }
                
                _db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(RemoteConnection);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert()
        {
            if (ModelState.IsValid)
            {
                if (RemoteConnection.Id == 0)
                {
                    //create
                    _db.RemoteConnection.Add(RemoteConnection);
                }
                else
                {
                    _db.RemoteConnection.Update(RemoteConnection);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(RemoteConnection);
        }

        #region API Calls
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _db.RemoteConnection.ToListAsync() });
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var ConnFromDb = await _db.RemoteConnection.FirstOrDefaultAsync(u => u.Id == id);
            if (ConnFromDb == null)
            {
                return Json(new { success = false, message = "Error while Deleting" });
            }
            _db.RemoteConnection.Remove(ConnFromDb);
            await _db.SaveChangesAsync();
            return Json(new { success = true, message = "Delete successfull" });
        }

        [HttpPost]
        public async Task<IActionResult> Disconnect(int id)
        {
            var ConnFromDb = await _db.RemoteConnection.FirstOrDefaultAsync(u => u.Id == id);
            if (ConnFromDb == null)
            {
                return Json(new { success = false, message = "Ayrılırken hata oluştu." });
            }

            if (ConnFromDb.BagliKisi != User.Identity.Name)
            {
                return Json(new { success = false, message = "Zaten bağlı değilsiniz." });
            }

            ConnFromDb.BagliKisi = null;
            ConnFromDb.BaglantiZamani = null;
            ConnFromDb.Note = null;
            await _db.SaveChangesAsync();
            return Json(new { success = true, message = "Ayrılma işlemi başarılı." });
        }
        #endregion
    }
}

RemoteConnectionQueueApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RemoteConnectionQueueApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css" />
    @*<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IdentityTestApp</a>*@
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="https://www.mbi.com.tr/content/images/logo/logo-1.png" width="150" height="50" alt=""></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial.cshtml" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white-50" asp-area="" asp-controller="Connections" asp-action="Index">Bağlantı Listesi</a>
                        </li>
                        @*<li class="nav-item">
                                <a class="nav-link text-white-50" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white-50" asp-area="" asp-controller="Books" asp-action="Index">Book List</a>
                            </li>*@
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class="footer-07">
        <div class="container">
            <!-- Row 1 Starts -->
            <div class="row row1">
                <!-- Social Icons Starts -->
                <div class="col-lg-3 col-md-3 col-sm-3 call-now text-white-50"><i class="fa fa-phone"></i> Telefon: <a href="">0 212 275 87 88</a></div>
                <!-- Social Icons Ends -->
                <div class="col-lg-6 col-md-6 col-sm-6 footer-logo"><a href="https://www.mbi.com.tr"><img src="https://www.mbi.com.tr/content/images/logo/logo-1.png" alt=""></a></div>
                <!-- Social Icons Starts -->
                <div class="col-lg-3 col-md-3 col-sm-3 mail text-white-50"><i class="fa fa-envelope"></i>MAİL: <a href="mailto:info@mbi.com.tr">info@mbi.com.tr</a></div>
                <!-- Social Icons Ends -->
            </div>
            <!-- Row 1 Ends -->
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>*@
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @await Component.InvokeAsync("Notyf")
    @RenderSection("Scripts", required: false)
</body>
</html>